#!/bin/bash
## install scripts to all openvz containers 
for arg in `vzlist -a -H -o ctid`
do
  echo "fix container $arg"
#vzctl exec $arg rpm -qa | grep http
#vzquota stat $arg
#vzquota show $arg
vzctl set $arg --nameserver 8.8.4.4 --nameserver 8.8.8.8 --save

#sed -i '/UserDir disabled/!s/UserDir disable/UserDir disabled/g' /home/private/$arg/etc/httpd/conf/httpd.conf && vzctl exec $arg service httpd restart
done

